<?php

namespace AppBundle\Repository;

/**
 * FormularzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormularzRepository extends \Doctrine\ORM\EntityRepository
{
}
